### ISSUE TITLE
How to stream multiply IP-Cameras

### ISSUE THREAD

**Issue by baur** [Zveroslav/node-rtsp-stream-jsmpeg#1]
Hi, good work, it works finally!
How to stream multiple IP-Cameras?

I need start stream when it was requested and stream that camera which was requested, is it possible?

**Comment by Zveroslav** [comment]
This liberty just wrapper of FFMPEG instance. For multiple this process you need run FFMPEG from docker containers.

**Comment by xiejianwei01** [comment]
I created the RTSP with VLC but it doesn't work

[rtsp @ 0000000000463200] method SETUP failed: 461 Client error
rtsp://localhost:8554/test: Unknown error

**Comment by xiejianwei01** [comment]
const options = {
  name: 'streamName',
  url: 'rtsp://localhost:8554/test',
  wsPort: 3333
}

stream = new Stream(options)
stream.start()

**Comment by Zveroslav** [comment]
It looks like an error from FFMPEG. I think you need to try to use another RTSP for the test.

**Comment by baur** [comment]
нельзя ли как то вот так:
https://github.com/databilim/rtsp-stream/blob/master/app.js
