### ISSUE TITLE
Can i use this for multiple camera ?

### ISSUE THREAD

**Issue by akakshuki** [Zveroslav/node-rtsp-stream-jsmpeg#5]

**Comment by iamir4g** [comment]
can you use it for multi-camera?

**Comment by akakshuki** [comment]
Yes, I have from 4 to 6 camera need to stream in my website.

**Comment by SilfridoReverol** [comment]
> Yes, I have from 4 to 6 camera need to stream in my website.

Were you able to stream all those cameras from a single server? I'm trying to stream just two cameras, but it seems that the whole thing dies if I try to initialize two streams at the time

**Comment by ekalaya** [comment]
how you do that?

**Comment by keanallen** [comment]
> Yes, I have from 4 to 6 camera need to stream in my website.

Is this how you di it?
```
const options1 = {
  name: 'streamName',
  url: 'rtsp://username:password@ipAddress:port/Streaming/Channels/001',
  wsPort: 3333
}

let stream1 = new Stream(options1)
stream1.start()

const options2 = {
  name: 'streamName',
  url: 'rtsp://username:password@ipAddress:port/Streaming/Channels/002',
  wsPort: 4444
}

let stream2 = new Stream(options2)
stream2.start()


```

**Comment by akakshuki** [comment]
>
